<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BukuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('buku')->insert([
            [
                'id_buku' => 1,
                'kode_buku' => 'NA001',
                'judul_buku' => 'Funiculi Funicula',
                'penulis' => 'Toshikazu Kawaguchi',
                'penerbit' => 'Poplar Publishing',
                'tanggal_terbit' => '2015-01-01',
                'kategori_id' => 5, // Drama
                'stok' => 10,
                'sampul' => 'funiculi.jpg',
                'deskripsi' => 'Novel tentang sebuah kafe misterius yang memungkinkan pengunjungnya melakukan perjalanan waktu dengan syarat tertentu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 2,
                'kode_buku' => 'SL001',
                'judul_buku' => 'Solo Leveling Vol. 1',
                'penulis' => 'Chugong',
                'penerbit' => 'D&C Media',
                'tanggal_terbit' => '2018-01-01',
                'kategori_id' => 1, // Fantasy / Action
                'stok' => 12,
                'sampul' => 'solo_leveling_1.jpg',
                'deskripsi' => 'Mengisahkan Sung Jin-Woo, hunter terlemah yang hampir tewas dalam dungeon berbahaya dan memperoleh kekuatan misterius untuk berkembang tanpa batas.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 3,
                'kode_buku' => 'SL002',
                'judul_buku' => 'Solo Leveling Vol. 2',
                'penulis' => 'Chugong',
                'penerbit' => 'D&C Media',
                'tanggal_terbit' => '2018-05-01',
                'kategori_id' => 1,
                'stok' => 12,
                'sampul' => 'solo_leveling_2.jpg',
                'deskripsi' => 'Jin-Woo mulai menyadari potensi kekuatannya dan memasuki dungeon berbahaya seorang diri demi menjadi lebih kuat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 4,
                'kode_buku' => 'SL003',
                'judul_buku' => 'Solo Leveling Vol. 3',
                'penulis' => 'Chugong',
                'penerbit' => 'D&C Media',
                'tanggal_terbit' => '2018-09-01',
                'kategori_id' => 1,
                'stok' => 12,
                'sampul' => 'solo_leveling_3.jpg',
                'deskripsi' => 'Kekuatan Jin-Woo berkembang pesat dan mulai menarik perhatian para guild besar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 5,
                'kode_buku' => 'SL004',
                'judul_buku' => 'Solo Leveling Vol. 4',
                'penulis' => 'Chugong',
                'penerbit' => 'D&C Media',
                'tanggal_terbit' => '2019-01-01',
                'kategori_id' => 1,
                'stok' => 12,
                'sampul' => 'solo_leveling_4.jpg',
                'deskripsi' => 'Jin-Woo membentuk pasukan bayangan dan menghadapi monster yang semakin kuat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 6,
                'kode_buku' => 'SL005',
                'judul_buku' => 'Solo Leveling Vol. 5',
                'penulis' => 'Chugong',
                'penerbit' => 'D&C Media',
                'tanggal_terbit' => '2019-06-01',
                'kategori_id' => 1,
                'stok' => 12,
                'sampul' => 'solo_leveling_5.jpg',
                'deskripsi' => 'Pertarungan skala besar terjadi dan Jin-Woo semakin dikenal sebagai hunter terkuat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 7,
                'kode_buku' => 'SL006',
                'judul_buku' => 'Solo Leveling Vol. 6',
                'penulis' => 'Chugong',
                'penerbit' => 'D&C Media',
                'tanggal_terbit' => '2019-10-01',
                'kategori_id' => 1,
                'stok' => 12,
                'sampul' => 'solo_leveling_6.jpg',
                'deskripsi' => 'Jin-Woo menghadapi ancaman yang jauh lebih besar dan mengungkap rahasia kekuatannya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 8,
                'kode_buku' => 'YN001',
                'judul_buku' => 'Your Name',
                'penulis' => 'Makoto Shinkai',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2016-06-18',
                'kategori_id' => 3, // Drama / Romance
                'stok' => 15,
                'sampul' => 'your_name_1.jpg',
                'deskripsi' => 'Kisah Mitsuha dan Taki yang secara misterius bertukar tubuh dan terhubung oleh takdir melintasi ruang dan waktu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 9,
                'kode_buku' => 'YN002',
                'judul_buku' => 'Your Name – Another Side: Earthbound',
                'penulis' => 'Makoto Shinkai',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2016-08-01',
                'kategori_id' => 3,
                'stok' => 10,
                'sampul' => 'your_name_earthbound.jpg',
                'deskripsi' => 'Cerita tambahan dari sudut pandang karakter lain yang memperluas dunia Your Name.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 10,
                'kode_buku' => 'YN003',
                'judul_buku' => 'Weathering With You',
                'penulis' => 'Makoto Shinkai',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2019-07-19',
                'kategori_id' => 3, // Drama / Romance / Supernatural
                'stok' => 12,
                'sampul' => 'weathering_with_you.jpg',
                'deskripsi' => 'Kisah Hodaka dan Hina yang memiliki kemampuan mengendalikan cuaca di tengah Tokyo yang terus diguyur hujan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 11,
                'kode_buku' => 'GR001',
                'judul_buku' => 'Grimgar of Fantasy and Ash Vol. 1',
                'penulis' => 'Ao Jyumonji',
                'penerbit' => 'Overlap',
                'tanggal_terbit' => '2013-06-25',
                'kategori_id' => 5, // Fantasy / Adventure
                'stok' => 10,
                'sampul' => 'grimgar_1.jpg',
                'deskripsi' => 'Sekelompok pemuda terbangun di dunia asing bernama Grimgar tanpa ingatan dan harus bertahan hidup sebagai prajurit sukarelawan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 12,
                'kode_buku' => 'GR002',
                'judul_buku' => 'Grimgar of Fantasy and Ash Vol. 2',
                'penulis' => 'Ao Jyumonji',
                'penerbit' => 'Overlap',
                'tanggal_terbit' => '2013-09-25',
                'kategori_id' => 5,
                'stok' => 10,
                'sampul' => 'grimgar_2.jpg',
                'deskripsi' => 'Kelompok Haruhiro menghadapi tantangan baru dan belajar bekerja sama demi bertahan hidup.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 13,
                'kode_buku' => 'GR003',
                'judul_buku' => 'Grimgar of Fantasy and Ash Vol. 3',
                'penulis' => 'Ao Jyumonji',
                'penerbit' => 'Overlap',
                'tanggal_terbit' => '2014-01-25',
                'kategori_id' => 5,
                'stok' => 10,
                'sampul' => 'grimgar_3.jpg',
                'deskripsi' => 'Pertarungan semakin berat dan kehilangan menjadi bagian dari perjalanan mereka.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 14,
                'kode_buku' => 'GR004',
                'judul_buku' => 'Grimgar of Fantasy and Ash Vol. 4',
                'penulis' => 'Ao Jyumonji',
                'penerbit' => 'Overlap',
                'tanggal_terbit' => '2014-05-25',
                'kategori_id' => 5,
                'stok' => 10,
                'sampul' => 'grimgar_4.jpg',
                'deskripsi' => 'Petualangan membawa mereka ke wilayah baru dengan musuh yang lebih berbahaya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 15,
                'kode_buku' => 'DAL001',
                'judul_buku' => 'Date A Live Vol. 1',
                'penulis' => 'Kōshi Tachibana',
                'penerbit' => 'Fujimi Shobo',
                'tanggal_terbit' => '2011-03-19',
                'kategori_id' => 12, // Fantasy / Romance / Action
                'stok' => 14,
                'sampul' => 'date_a_live_1.jpg',
                'deskripsi' => 'Shido Itsuka harus menyelamatkan dunia dengan cara unik: mengencani para Spirit yang mengancam umat manusia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 16,
                'kode_buku' => 'DAL002',
                'judul_buku' => 'Date A Live Vol. 2',
                'penulis' => 'Kōshi Tachibana',
                'penerbit' => 'Fujimi Shobo',
                'tanggal_terbit' => '2011-06-18',
                'kategori_id' => 12,
                'stok' => 14,
                'sampul' => 'date_a_live_2.jpg',
                'deskripsi' => 'Spirit baru muncul dan Shido kembali menjalankan misi berbahaya dengan cara romantis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 17,
                'kode_buku' => 'DAL003',
                'judul_buku' => 'Date A Live Vol. 3',
                'penulis' => 'Kōshi Tachibana',
                'penerbit' => 'Fujimi Shobo',
                'tanggal_terbit' => '2011-09-17',
                'kategori_id' => 12,
                'stok' => 14,
                'sampul' => 'date_a_live_3.jpg',
                'deskripsi' => 'Hubungan Shido dengan para Spirit semakin kompleks di tengah ancaman organisasi misterius.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 18,
                'kode_buku' => 'DAL004',
                'judul_buku' => 'Date A Live Vol. 4',
                'penulis' => 'Kōshi Tachibana',
                'penerbit' => 'Fujimi Shobo',
                'tanggal_terbit' => '2012-01-20',
                'kategori_id' => 12,
                'stok' => 14,
                'sampul' => 'date_a_live_4.jpg',
                'deskripsi' => 'Konflik besar muncul saat kekuatan Spirit mulai lepas kendali.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 19,
                'kode_buku' => 'DAL005',
                'judul_buku' => 'Date A Live Vol. 16',
                'penulis' => 'Kōshi Tachibana',
                'penerbit' => 'Fujimi Shobo',
                'tanggal_terbit' => '2017-05-19',
                'kategori_id' => 12,
                'stok' => 14,
                'sampul' => 'date_a_live_16.jpg',
                'deskripsi' => 'Pertarungan semakin intens dan rahasia dunia Spirit mulai terungkap.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 20,
                'kode_buku' => 'AB001',
                'judul_buku' => 'Angel Beats! – Track ZERO',
                'penulis' => 'Jun Maeda',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2010-05-10',
                'kategori_id' => 10, // Drama / Supernatural
                'stok' => 10,
                'sampul' => 'angel_beats_zero.jpg',
                'deskripsi' => 'Prekuel yang menceritakan awal terbentuknya SSS dan perjuangan mereka di dunia setelah kematian.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 21,
                'kode_buku' => 'AB002',
                'judul_buku' => 'Angel Beats! – Last Operation Vol. 1',
                'penulis' => 'Jun Maeda',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2017-12-20',
                'kategori_id' => 10,
                'stok' => 10,
                'sampul' => 'angel_beats_last_1.jpg',
                'deskripsi' => 'Versi novelisasi yang memperluas cerita anime dengan sudut pandang dan detail baru.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 22,
                'kode_buku' => 'AB003',
                'judul_buku' => 'Angel Beats! – Last Operation Vol. 2',
                'penulis' => 'Jun Maeda',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2018-06-20',
                'kategori_id' => 10,
                'stok' => 10,
                'sampul' => 'angel_beats_last_2.jpg',
                'deskripsi' => 'Kelanjutan kisah emosional yang menggali masa lalu para karakter.',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'id_buku' => 23,
                'kode_buku' => 'VE001',
                'judul_buku' => 'Violet Evergarden Vol. 1',
                'penulis' => 'Kana Akatsuki',
                'penerbit' => 'KA Esuma Bunko',
                'tanggal_terbit' => '2015-12-25',
                'kategori_id' => 4, // Drama / Slice of Life
                'stok' => 13,
                'sampul' => 'violet_evergarden_1.jpg',
                'deskripsi' => 'Violet, mantan prajurit muda, berusaha memahami arti kata “aku mencintaimu” melalui pekerjaannya sebagai penulis surat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 24,
                'kode_buku' => 'VE002',
                'judul_buku' => 'Violet Evergarden Vol. 2',
                'penulis' => 'Kana Akatsuki',
                'penerbit' => 'KA Esuma Bunko',
                'tanggal_terbit' => '2016-01-15',
                'kategori_id' => 4,
                'stok' => 13,
                'sampul' => 'violet_evergarden_2.jpg',
                'deskripsi' => 'Perjalanan Violet berlanjut dengan kisah-kisah klien yang penuh emosi dan makna kehidupan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 25,
                'kode_buku' => 'VE003',
                'judul_buku' => 'Violet Evergarden Gaiden',
                'penulis' => 'Kana Akatsuki',
                'penerbit' => 'KA Esuma Bunko',
                'tanggal_terbit' => '2018-03-23',
                'kategori_id' => 4,
                'stok' => 11,
                'sampul' => 'violet_evergarden_gaiden.jpg',
                'deskripsi' => 'Kumpulan cerita sampingan yang memperdalam dunia dan karakter Violet Evergarden.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 26,
                'kode_buku' => 'SAO001',
                'judul_buku' => 'Sword Art Online Vol. 1: Aincrad',
                'penulis' => 'Reki Kawahara',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2009-04-10',
                'kategori_id' => 6, // Fantasy / Action / Sci-Fi
                'stok' => 15,
                'sampul' => 'sao_1.jpg',
                'deskripsi' => 'Kirito terjebak dalam game VRMMO mematikan dan harus menaklukkan 100 lantai Aincrad untuk bisa keluar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 27,
                'kode_buku' => 'SAO002',
                'judul_buku' => 'Sword Art Online Vol. 2: Aincrad',
                'penulis' => 'Reki Kawahara',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2009-08-10',
                'kategori_id' => 6,
                'stok' => 15,
                'sampul' => 'sao_2.jpg',
                'deskripsi' => 'Kisah lanjutan perjuangan Kirito dan Asuna menghadapi dunia Aincrad yang brutal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 28,
                'kode_buku' => 'SAO003',
                'judul_buku' => 'Sword Art Online Vol. 3: Fairy Dance',
                'penulis' => 'Reki Kawahara',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2009-12-10',
                'kategori_id' => 6,
                'stok' => 15,
                'sampul' => 'sao_3.jpg',
                'deskripsi' => 'Kirito memasuki dunia game baru untuk menyelamatkan Asuna yang terjebak di Alfheim Online.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 29,
                'kode_buku' => 'SAO004',
                'judul_buku' => 'Sword Art Online Vol. 4: Fairy Dance',
                'penulis' => 'Reki Kawahara',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2010-04-10',
                'kategori_id' => 6,
                'stok' => 15,
                'sampul' => 'sao_4.jpg',
                'deskripsi' => 'Pertarungan klimaks Kirito melawan penguasa Alfheim.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 30,
                'kode_buku' => 'SAO005',
                'judul_buku' => 'Sword Art Online Vol. 5: Phantom Bullet',
                'penulis' => 'Reki Kawahara',
                'penerbit' => 'ASCII Media Works',
                'tanggal_terbit' => '2010-08-10',
                'kategori_id' => 6,
                'stok' => 15,
                'sampul' => 'sao_5.jpg',
                'deskripsi' => 'Kirito menyelidiki kasus misterius di game Gun Gale Online.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 31,
                'kode_buku' => 'LH001',
                'judul_buku' => 'Log Horizon Vol. 1: The Beginning of Another World',
                'penulis' => 'Mamare Touno',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2011-03-31',
                'kategori_id' => 2, // Fantasy / Adventure
                'stok' => 13,
                'sampul' => 'log_horizon_1.jpg',
                'deskripsi' => 'Shiroe dan ribuan pemain terjebak dalam game Elder Tale dan harus membangun peradaban baru.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 32,
                'kode_buku' => 'LH002',
                'judul_buku' => 'Log Horizon Vol. 2: The Knights of Camelot',
                'penulis' => 'Mamare Touno',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2011-08-31',
                'kategori_id' => 2,
                'stok' => 13,
                'sampul' => 'log_horizon_2.jpg',
                'deskripsi' => 'Konflik antar guild mulai muncul saat dunia baru ini berkembang.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 33,
                'kode_buku' => 'LH003',
                'judul_buku' => 'Log Horizon Vol. 3: The Gold of the Kunie Clan',
                'penulis' => 'Mamare Touno',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2012-02-29',
                'kategori_id' => 2,
                'stok' => 13,
                'sampul' => 'log_horizon_3.jpg',
                'deskripsi' => 'Intrik politik dan ekonomi menjadi kunci bertahan hidup di dunia Elder Tale.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 34,
                'kode_buku' => 'LH004',
                'judul_buku' => 'Log Horizon Vol. 4: The Feast of the Gods',
                'penulis' => 'Mamare Touno',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2012-09-30',
                'kategori_id' => 2,
                'stok' => 13,
                'sampul' => 'log_horizon_4.jpg',
                'deskripsi' => 'Rahasia dunia game perlahan terungkap seiring munculnya ancaman baru.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 35,
                'kode_buku' => 'YS001',
                'judul_buku' => 'Youjo Senki Vol. 1: Deus lo Vult',
                'penulis' => 'Carlo Zen',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2013-10-31',
                'kategori_id' => 16, // Military Fantasy
                'stok' => 11,
                'sampul' => 'youjo_senki_1.jpg',
                'deskripsi' => 'Seorang pria bereinkarnasi sebagai gadis kecil bernama Tanya dan terjun ke medan perang dunia magis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 36,
                'kode_buku' => 'YS002',
                'judul_buku' => 'Youjo Senki Vol. 2: Plus Ultra',
                'penulis' => 'Carlo Zen',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2014-03-31',
                'kategori_id' => 16,
                'stok' => 11,
                'sampul' => 'youjo_senki_2.jpg',
                'deskripsi' => 'Tanya memimpin pasukan elit dalam misi-misi berbahaya di medan perang.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 37,
                'kode_buku' => 'YS003',
                'judul_buku' => 'Youjo Senki Vol. 3',
                'penulis' => 'Carlo Zen',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2014-08-30',
                'kategori_id' => 16,
                'stok' => 11,
                'sampul' => 'youjo_senki_3.jpg',
                'deskripsi' => 'Perang semakin meluas dan strategi Tanya makin kejam serta efektif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 38,
                'kode_buku' => 'YS004',
                'judul_buku' => 'Youjo Senki Vol. 4',
                'penulis' => 'Carlo Zen',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2015-01-30',
                'kategori_id' => 16,
                'stok' => 11,
                'sampul' => 'youjo_senki_4.jpg',
                'deskripsi' => 'Konflik global memuncak dan Tanya menghadapi musuh yang lebih berbahaya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 39,
                'kode_buku' => 'YS005',
                'judul_buku' => 'Youjo Senki Vol. 5',
                'penulis' => 'Carlo Zen',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2015-06-30',
                'kategori_id' => 16, // Military Fantasy
                'stok' => 11,
                'sampul' => 'youjo_senki_5.jpg',
                'deskripsi' => 'Tanya menghadapi front perang baru dengan strategi brutal yang mengguncang dunia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 40,
                'kode_buku' => 'YS006',
                'judul_buku' => 'Youjo Senki Vol. 6',
                'penulis' => 'Carlo Zen',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2015-12-26',
                'kategori_id' => 16,
                'stok' => 11,
                'sampul' => 'youjo_senki_6.jpg',
                'deskripsi' => 'Pertempuran skala besar menentukan arah masa depan kekaisaran dan dunia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'id_buku' => 41,
                'kode_buku' => 'JJK001',
                'judul_buku' => 'Jujutsu Kaisen Vol. 1',
                'penulis' => 'Gege Akutami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2018-07-04',
                'kategori_id' => 15, // Action / Supernatural
                'stok' => 16,
                'sampul' => 'jjk_1.jpg',
                'deskripsi' => 'Yuji Itadori menelan jari terkutuk Sukuna dan terjun ke dunia penyihir jujutsu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 42,
                'kode_buku' => 'JJK002',
                'judul_buku' => 'Jujutsu Kaisen Vol. 2',
                'penulis' => 'Gege Akutami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2018-09-04',
                'kategori_id' => 15,
                'stok' => 16,
                'sampul' => 'jjk_2.jpg',
                'deskripsi' => 'Pelatihan berbahaya dimulai di bawah bimbingan Gojo Satoru.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 43,
                'kode_buku' => 'JJK003',
                'judul_buku' => 'Jujutsu Kaisen Vol. 3',
                'penulis' => 'Gege Akutami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2018-11-02',
                'kategori_id' => 15,
                'stok' => 16,
                'sampul' => 'jjk_3.jpg',
                'deskripsi' => 'Pertarungan sengit melawan kutukan tingkat tinggi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 44,
                'kode_buku' => 'JJK004',
                'judul_buku' => 'Jujutsu Kaisen Vol. 4',
                'penulis' => 'Gege Akutami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2019-01-04',
                'kategori_id' => 15,
                'stok' => 16,
                'sampul' => 'jjk_4.jpg',
                'deskripsi' => 'Ancaman besar mulai muncul dari dunia kutukan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 45,
                'kode_buku' => 'JJK005',
                'judul_buku' => 'Jujutsu Kaisen Vol. 5',
                'penulis' => 'Gege Akutami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2019-03-04',
                'kategori_id' => 15,
                'stok' => 16,
                'sampul' => 'jjk_5.jpg',
                'deskripsi' => 'Konflik semakin rumit dengan munculnya musuh baru.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 46,
                'kode_buku' => 'JJK006',
                'judul_buku' => 'Jujutsu Kaisen Vol. 6',
                'penulis' => 'Gege Akutami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2019-05-02',
                'kategori_id' => 15,
                'stok' => 16,
                'sampul' => 'jjk_6.jpg',
                'deskripsi' => 'Pertempuran epik menguji batas kemampuan para penyihir.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 47,
                'kode_buku' => 'WB001',
                'judul_buku' => 'Wind Breaker Vol. 1',
                'penulis' => 'Jo Yongseok',
                'penerbit' => 'Naver Webtoon',
                'tanggal_terbit' => '2019-01-10',
                'kategori_id' => 14, // Manhwa / Webtoon / Action
                'stok' => 15,
                'sampul' => 'wind_breaker_1.jpg',
                'deskripsi' => 'Jin Woo pindah ke kota baru dan menghadapi tantangan tim sepeda jalanan elit.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 48,
                'kode_buku' => 'WB002',
                'judul_buku' => 'Wind Breaker Vol. 2',
                'penulis' => 'Jo Yongseok',
                'penerbit' => 'Naver Webtoon',
                'tanggal_terbit' => '2019-05-10',
                'kategori_id' => 14,
                'stok' => 15,
                'sampul' => 'wind_breaker_2.jpg',
                'deskripsi' => 'Pertemuan dengan rival baru memicu kompetisi sepeda yang menegangkan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 49,
                'kode_buku' => 'WB003',
                'judul_buku' => 'Wind Breaker Vol. 3',
                'penulis' => 'Jo Yongseok',
                'penerbit' => 'Naver Webtoon',
                'tanggal_terbit' => '2019-09-10',
                'kategori_id' => 14,
                'stok' => 15,
                'sampul' => 'wind_breaker_3.jpg',
                'deskripsi' => 'Tim Jin Woo mulai menunjukkan kekompakan dan strategi untuk mengalahkan rival.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 50,
                'kode_buku' => 'WB004',
                'judul_buku' => 'Wind Breaker Vol. 4',
                'penulis' => 'Jo Yongseok',
                'penerbit' => 'Naver Webtoon',
                'tanggal_terbit' => '2020-01-10',
                'kategori_id' => 14,
                'stok' => 15,
                'sampul' => 'wind_breaker_4.jpg',
                'deskripsi' => 'Konflik semakin seru dengan turnamen sepeda yang penuh tantangan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 51,
                'kode_buku' => 'HY001',
                'judul_buku' => 'Hyouka Vol. 1',
                'penulis' => 'Honobu Yonezawa',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2001-04-10',
                'kategori_id' => 8, // Mystery
                'stok' => 12,
                'sampul' => 'hyouka_1.jpg',
                'deskripsi' => 'Oreki Houtarou yang hemat energi bergabung klub Sastra Klasik dan terlibat memecahkan misteri kecil di sekolah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 52,
                'kode_buku' => 'HY002',
                'judul_buku' => 'Hyouka Vol. 2',
                'penulis' => 'Honobu Yonezawa',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2002-03-15',
                'kategori_id' => 8,
                'stok' => 12,
                'sampul' => 'hyouka_2.jpg',
                'deskripsi' => 'Oreki dan teman-temannya memecahkan misteri klasik dengan deduksi cerdas dan intrik sekolah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 53,
                'kode_buku' => 'HY003',
                'judul_buku' => 'Hyouka Vol. 3',
                'penulis' => 'Honobu Yonezawa',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2003-07-10',
                'kategori_id' => 8,
                'stok' => 12,
                'sampul' => 'hyouka_3.jpg',
                'deskripsi' => 'Klub Sastra Klasik menghadapi kasus misterius baru yang menguji kemampuan observasi Oreki.',
                'created_at' => now(),
                'updated_at' => now(),
            ],



            [
                'id_buku' => 54,
                'kode_buku' => 'SOE001',
                'judul_buku' => 'Seraph of the End Vol. 1',
                'penulis' => 'Takaya Kagami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2013-01-04',
                'kategori_id' => 19, // Dark Fantasy / Action
                'stok' => 14,
                'sampul' => 'seraph_1.jpg',
                'deskripsi' => 'Dunia hancur oleh virus misterius dan manusia bertarung melawan vampir demi bertahan hidup.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 55,
                'kode_buku' => 'SOE002',
                'judul_buku' => 'Seraph of the End Vol. 2',
                'penulis' => 'Takaya Kagami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2013-05-02',
                'kategori_id' => 19,
                'stok' => 14,
                'sampul' => 'seraph_2.jpg',
                'deskripsi' => 'Yuichiro bergabung dengan pasukan pembasmi vampir dan menjalani pelatihan brutal.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 56,
                'kode_buku' => 'SOE003',
                'judul_buku' => 'Seraph of the End Vol. 3',
                'penulis' => 'Takaya Kagami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2013-09-04',
                'kategori_id' => 19,
                'stok' => 14,
                'sampul' => 'seraph_3.jpg',
                'deskripsi' => 'Konflik antara manusia dan vampir semakin memanas.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 57,
                'kode_buku' => 'SOE004',
                'judul_buku' => 'Seraph of the End Vol. 4',
                'penulis' => 'Takaya Kagami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2014-01-04',
                'kategori_id' => 19,
                'stok' => 14,
                'sampul' => 'seraph_4.jpg',
                'deskripsi' => 'Rahasia eksperimen seraph mulai terungkap.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 58,
                'kode_buku' => 'SOE005',
                'judul_buku' => 'Seraph of the End Vol. 5',
                'penulis' => 'Takaya Kagami',
                'penerbit' => 'Shueisha',
                'tanggal_terbit' => '2014-05-02',
                'kategori_id' => 19,
                'stok' => 14,
                'sampul' => 'seraph_5.jpg',
                'deskripsi' => 'Pertarungan besar menentukan nasib umat manusia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 59,
                'kode_buku' => 'KAB001',
                'judul_buku' => 'Kabaneri of the Iron Fortress – Part 1: Gathering Light',
                'penulis' => 'Ichirō Ōkouchi',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2016-06-03',
                'kategori_id' => 21, // Action / Post-Apocalyptic
                'stok' => 12,
                'sampul' => 'kabaneri_1.jpg',
                'deskripsi' => 'Umat manusia bertahan di dalam benteng melawan makhluk undead bernama Kabane.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 60,
                'kode_buku' => 'KAB002',
                'judul_buku' => 'Kabaneri of the Iron Fortress – Part 2: Burning Life',
                'penulis' => 'Ichirō Ōkouchi',
                'penerbit' => 'Kadokawa',
                'tanggal_terbit' => '2016-08-05',
                'kategori_id' => 21,
                'stok' => 12,
                'sampul' => 'kabaneri_2.jpg',
                'deskripsi' => 'Ikoma dan Mumei menghadapi ancaman Kabane yang semakin mematikan di tengah kekacauan dunia.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


            [
                'id_buku' => 61,
                'kode_buku' => 'KOT001',
                'judul_buku' => 'King of Thorn Vol. 1',
                'penulis' => 'Yuji Iwahara',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2002-10-25',
                'kategori_id' => 21, // Sci-Fi / Horror / Mystery
                'stok' => 10,
                'sampul' => 'king_of_thorn_1.jpg',
                'deskripsi' => 'Manusia terbangun dari cryostasis di dunia yang dipenuhi makhluk mematikan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 62,
                'kode_buku' => 'KOT002',
                'judul_buku' => 'King of Thorn Vol. 2',
                'penulis' => 'Yuji Iwahara',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2003-03-25',
                'kategori_id' => 21,
                'stok' => 10,
                'sampul' => 'king_of_thorn_2.jpg',
                'deskripsi' => 'Rahasia dunia baru mulai terungkap di balik teror monster.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 63,
                'kode_buku' => 'KOT003',
                'judul_buku' => 'King of Thorn Vol. 3',
                'penulis' => 'Yuji Iwahara',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2003-08-25',
                'kategori_id' => 21,
                'stok' => 10,
                'sampul' => 'king_of_thorn_3.jpg',
                'deskripsi' => 'Konflik antar manusia bertambah rumit di tengah kehancuran.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_buku' => 64,
                'kode_buku' => 'KOT004',
                'judul_buku' => 'King of Thorn Vol. 4',
                'penulis' => 'Yuji Iwahara',
                'penerbit' => 'Enterbrain',
                'tanggal_terbit' => '2004-01-25',
                'kategori_id' => 21,
                'stok' => 10,
                'sampul' => 'king_of_thorn_4.jpg',
                'deskripsi' => 'Pertarungan bertahan hidup mencapai titik kritis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}
