<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('user')->insert([

            /* =====================
               ADMIN
               ===================== */
            [
                'nama' => 'Administrator',
                'username' => 'admin',
                'password' => Hash::make('admin123'),
                'status_akun' => 'aktif',
                'role_id' => 1,
                'profil' => 'admin.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* =====================
               USER / SISWA
               ===================== */

            [
                'nama' => 'Ahmad Fauzi',
                'username' => 'ahmad',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Budi Santoso',
                'username' => 'budi',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Citra Lestari',
                'username' => 'citra',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Deni Pratama',
                'username' => 'deni',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Eka Putri',
                'username' => 'eka',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fajar Hidayat',
                'username' => 'fajar',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Gita Anggraini',
                'username' => 'gita',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hendra Wijaya',
                'username' => 'hendra',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Indah Sari',
                'username' => 'indah',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Joko Prasetyo',
                'username' => 'joko',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama' => 'Sutsuji Erik',
                'username' => 'rik-r',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kurniawan Saputra',
                'username' => 'kurniawan',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lia Ramadhani',
                'username' => 'lia',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Muhammad Rizki',
                'username' => 'rizki',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nabila Putri',
                'username' => 'nabila',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Oka Pradana',
                'username' => 'oka',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Putri Ayu',
                'username' => 'putri',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Qori Annisa',
                'username' => 'qori',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rahmat Hidayat',
                'username' => 'rahmat',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Siti Aisyah',
                'username' => 'aisyah',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Taufik Akbar',
                'username' => 'taufik',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama' => 'User 21',
                'username' => 'user21',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'User 22',
                'username' => 'user22',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'User 23',
                'username' => 'user23',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /* ... */

            [
                'nama' => 'Yoshi Samsul',
                'username' => 'samsul',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'nama' => 'Andi Prasetyo',
                'username' => 'andi21',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bella Kartika',
                'username' => 'bella22',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Cahyo Nugroho',
                'username' => 'cahyo23',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dewi Anggraini',
                'username' => 'dewi24',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Eko Saputro',
                'username' => 'eko25',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fitri Handayani',
                'username' => 'fitri26',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Galih Permana',
                'username' => 'galih27',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Hana Safitri',
                'username' => 'hana28',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ilham Maulana',
                'username' => 'ilham29',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Jessica Putri',
                'username' => 'jessica30',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kevin Aditya',
                'username' => 'kevin31',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Larasati Putri',
                'username' => 'laras32',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mahendra Wijaya',
                'username' => 'mahendra33',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nina Oktaviani',
                'username' => 'nina34',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Omar Farhan',
                'username' => 'omar35',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Putra Ramadhan',
                'username' => 'putra36',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Qais Rahman',
                'username' => 'qais37',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rina Puspita',
                'username' => 'rina38',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Surya Dharma',
                'username' => 'surya39',
                'password' => Hash::make('password'),
                'status_akun' => 'aktif',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tania Maharani',
                'username' => 'tania40',
                'password' => Hash::make('password'),
                'status_akun' => 'pending',
                'role_id' => 2,
                'profil' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}
