<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('user')->insert([
            [
                'id_user' => 1,
                'nama' => 'Admin',
                'username' => 'admin',
                'password' => Hash::make('password'),
                'role_id' => 1,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 2,
                'nama' => 'Reiga Oliymore Clay',
                'username' => 'reiga',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 3,
                'nama' => 'Akira Tanaka',
                'username' => 'akira',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'akira.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 4,
                'nama' => 'Hiroshi Nakamura',
                'username' => 'hiroshi',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 5,
                'nama' => 'Li Wei',
                'username' => 'liwei',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'liwei.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 6,
                'nama' => 'Zhang Min',
                'username' => 'zhangmin',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 7,
                'nama' => 'Ahmed Al-Farisi',
                'username' => 'ahmed',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'ahmed.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 8,
                'nama' => 'Kenji Sato',
                'username' => 'kenji',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 9,
                'nama' => 'Yuki Mori',
                'username' => 'yuki',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'yuki.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 10,
                'nama' => 'Wang Hao',
                'username' => 'wanghao',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'wanghao.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 11,
                'nama' => 'Chen Yu',
                'username' => 'chenyu',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'chenyu.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 12,
                'nama' => 'Omar Al-Hakim',
                'username' => 'omar',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 13,
                'nama' => 'Takeshi Watanabe',
                'username' => 'takeshi',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 14,
                'nama' => 'Soo Jin Park',
                'username' => 'soojin',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'soojin.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 15,
                'nama' => 'Abdul Rahman',
                'username' => 'abdul',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 16,
                'nama' => 'Samuel Johnson',
                'username' => 'samuel',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'samuel.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 17,
                'nama' => 'David Miller',
                'username' => 'davidm',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 18,
                'nama' => 'Kofi Mensah',
                'username' => 'kofi',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 19,
                'nama' => 'Aisha Noor',
                'username' => 'aisha',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'aisha.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 20,
                'nama' => 'Joon Ho Kim',
                'username' => 'joonho',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 21,
                'nama' => 'Min Jae Lee',
                'username' => 'minjae',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'minjae.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 22,
                'nama' => 'Yusuf Al-Karim',
                'username' => 'yusuf',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 23,
                'nama' => 'Fatima Zahra',
                'username' => 'fatima',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'fatima.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 24,
                'nama' => 'Michael Brown',
                'username' => 'michael',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 25,
                'nama' => 'Emily Carter',
                'username' => 'emily',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'emily.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 26,
                'nama' => 'Tariq Hassan',
                'username' => 'tariq',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 27,
                'nama' => 'Said Al-Mansur',
                'username' => 'said',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'said.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 28,
                'nama' => 'Kwame Boateng',
                'username' => 'kwame',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 29,
                'nama' => 'Nia Okafor',
                'username' => 'nia',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => 'nia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_user' => 30,
                'nama' => 'Ethan Walker',
                'username' => 'ethan',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'profil' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}
